Repository CastledChess/Front, pull requests merged in 2024-10, with the labels that each got.

#37 fix: update file paths in eslint.config.js
  eslint.config.js
Labels: chore

#43 Fix Chessboard UI Bugs
  src/components/Sections/Chessboard/Chessboard.tsx
Labels: fix, improvement

#46 chore: Adding shadcn chore and the component "button"
  components.json
  package-lock.json
  package.json
  src/components/ui/button.tsx
  src/lib/utils.ts
  src/styles/index.css
  tailwind.config.js
  tsconfig.json
  vite.config.ts
Labels: feature, chore

#45 Stockfish API
  src/components/Sections/Chessboard/Chessboard.tsx
  src/contexts/analysisContext.tsx
  src/pages/Analysis/Analysis.tsx
  src/types/analysis.ts
  tailwind.config.js
Labels: feature, improvement

#49 feat(analysis): implemented ui layout based on the mockups
  src/app.tsx
  src/components/chessboard/chessboard.tsx
  src/components/playerinfo/playerinfo.tsx
  src/pages/analysis/analysis.tsx
  src/pages/analysis/start-analysis.tsx
  src/store/analysis.ts
  src/types/analysis.ts
Labels: feature
