Repository CastledChess/Front, pull requests merged in 2024-12, with the labels that each got.

#85 Comment Linter in Pre-Commit
  .husky/pre-commit
  src/lib/analysis.ts
  src/pages/analysis/start-analysis.tsx
Labels: chore, fix

#87 Improve/caching
  eslint.config.js
  package-lock.json
  package.json
  public/service-worker.js
  src/components/ui/select.tsx
  src/lib/analysis.ts
  src/main.tsx
  src/pages/analysis/start-analysis.tsx
  src/schema/analysis.ts
  src/services/cache/cache.service.ts
  tsconfig.node.tsbuildinfo
  tsconfig.tsbuildinfo
  vite.config.js
  vite.config.ts
Labels: improvement

#89 chore: add favicon
  index.html
  public/logo.svg
  public/vite.svg
Labels: chore

#88 chore(analysis): added translations for the start-analysis page
  src/i18n.config.ts
  src/i18n/locales/en/analysis.json
  src/i18n/locales/fr/analysis.json
  src/lib/opening.ts
  src/pages/analysis/analysis.tsx
  src/pages/analysis/start-analysis.tsx
Labels: chore, improvement

#91 Feat/nav bar
  package-lock.json
  package.json
  src/assets/logo/castled-black-logo.png
  src/assets/logo/castled-white-logo.png
  src/assets/logo/castled_tiny-black-logo.png
  src/assets/logo/castled_tiny-white-logo.png
  src/components/navbar/navbar.tsx
  src/components/ui/dropdown-menu.tsx
  src/components/ui/navigation-menu.tsx
  src/i18n/locales/en/navbar.json
  src/i18n/locales/fr/navbar.json
Labels: feature

#70 Add profile page
  src/app.tsx
  src/assets/icons/profile_picture.jpg
  src/components/navbar/navbar.tsx
  src/i18n/locales/en/profile.json
  src/i18n/locales/fr/profile.json
  src/pages/profile/profile.tsx
  src/schema/profile.ts
Labels: feature

#92 Feat/analysis persistence
  eslint.config.js
  src/api/analysis.ts
  src/api/index.ts
  src/app.tsx
  src/pages/analysis/analysis.tsx
  src/pages/start-analysis/start-analysis.tsx
  src/store/analysis.ts
Labels: feature

#94 Prod
  eslint.config.js
  index.html
  package-lock.json
  package.json
  public/logo.svg
  public/service-worker.js
  public/vite.svg
  src/api/analysis.ts
  src/api/chesscom.ts
  src/api/history.ts
  src/api/index.ts
  src/api/lichessorg.ts
  src/app.tsx
  src/assets/icons/profile_picture.jpg
  src/assets/logo/castled-black-logo.png
  src/assets/logo/castled-white-logo.png
  src/assets/logo/castled_tiny-black-logo.png
  src/assets/logo/castled_tiny-white-logo.png
  src/components/chessboard/base.css
  src/components/chessboard/chessboard-tooltip.tsx
  src/components/chessboard/chessboard.tsx
  src/components/navbar/navbar.tsx
  src/components/ui/calendar.tsx
  src/components/ui/checkbox.tsx
  src/components/ui/command.tsx
  src/components/ui/dropdown-menu.tsx
  src/components/ui/navigation-menu.tsx
  src/components/ui/select.tsx
  src/components/ui/table.tsx
  src/i18n.config.ts
  src/i18n/locales/en/analysis.json
  src/i18n/locales/en/history.json
  src/i18n/locales/en/navbar.json
  src/i18n/locales/en/profile.json
  src/i18n/locales/fr/analysis.json
  src/i18n/locales/fr/history.json
  src/i18n/locales/fr/navbar.json
  src/i18n/locales/fr/profile.json
  src/lib/analysis.ts
  src/lib/opening.ts
  src/main.tsx
  src/pages/analysis/analysis.tsx
  src/pages/analysis/start-analysis.tsx
  src/pages/history/columns.tsx
  src/pages/history/data-table.tsx
  src/pages/history/history-page.tsx
  src/pages/login.tsx
  src/pages/profile/profile.tsx
  src/pages/register.tsx
  src/pages/start-analysis/chesscom-select.tsx
  src/pages/start-analysis/lichessorg-select.tsx
  src/pages/start-analysis/start-analysis.tsx
  src/schema/analysis.ts
  src/schema/profile.ts
  src/services/cache/cache.service.ts
  src/store/analysis.ts
  tsconfig.node.tsbuildinfo
  tsconfig.tsbuildinfo
  vite.config.js
  vite.config.ts
Labels: feature
