Repository CastledChess/Front, pull requests merged in 2024-11, with the labels that each got.

#54 ops(vercel): add rewrite config
  vercel.json
Labels: ops

#56 Feat/auth
  .env.example
  .gitignore
  index.html
  package-lock.json
  package.json
  src/api/auth.ts
  src/api/index.ts
  src/app.tsx
  src/assets/icons/chess_logo.png
  src/assets/icons/lichess.png
  src/components/Sections/Navbar/Navbar.tsx
  src/components/navbar/navbar.tsx
  src/pages/login.tsx
  src/pages/register.tsx
  src/schema/auth.ts
  src/store/auth.ts
Labels: feature

#63 Improv/analysis
  src/components/evalchart/evalchart.tsx
  src/lib/analysis.ts
  src/pages/analysis/analysis.tsx
  src/pages/analysis/classifications.ts
  src/services/stockfish/uci-parser.service.ts
  src/types/analysis.ts
Labels: feature, fix, improvement

#66 feat: add service workers for caching engines
  package-lock.json
  package.json
  vite.config.ts
Labels: feature, ops

#65 fix(navbar): replace radix links with react router links for fluid na…
  src/components/navbar/navbar.tsx
Labels: fix

#77 feat(i18n): setup i18n
  README.md
  package-lock.json
  package.json
  src/i18n.config.ts
  src/i18n/locales/en/common.json
  src/i18n/locales/fr/common.json
  src/i18n/translations.md
  src/main.tsx
  src/pages/dashboard/dashboard.tsx
Labels: feature

#76 Feat/register page
  eslint.config.js
  package-lock.json
  package.json
  src/app.tsx
  src/assets/icons/chess_logo.png
  src/assets/icons/lichess.png
  src/components/chessboard/base.css
  src/components/navbar/navbar.tsx
  src/components/theme-provider.tsx
  src/components/ui/card.tsx
  src/components/ui/form.tsx
  src/components/ui/form_button.tsx
  src/components/ui/input.tsx
  src/components/ui/navigation-menu.tsx
  src/pages/dashboard/dashboard.tsx
  src/pages/dashboard/overview.tsx
  src/pages/register/register.tsx
  src/styles/autofill.css
  src/styles/index.css
  tailwind.config.js
  tsconfig.node.tsbuildinfo
  tsconfig.tsbuildinfo
  vite.config.d.ts
  vite.config.js
Labels: feature

#79 Feat/login page
  eslint.config.js
  package-lock.json
  package.json
  src/app.tsx
  src/components/navbar/navbar.tsx
  src/components/ui/card.tsx
  src/components/ui/input.tsx
  src/pages/dashboard/overview.tsx
  src/pages/login/login.tsx
  src/pages/register/register.tsx
  tailwind.config.js
Labels: feature, style
