Repository CastledChess/Front, pull requests merged in 2025-02, with the labels that each got.

#96 Improve/analysis
  eslint.config.js
  package-lock.json
  package.json
  src/app.tsx
  src/components/evalbar/evalbar.tsx
  src/components/evalchart/evalchart.tsx
  src/components/ui/resizable.tsx
  src/data/classifications.ts
  src/lib/analysis.ts
  src/pages/analysis/analysis-old.tsx
  src/pages/analysis/analysis.tsx
  src/pages/analysis/droppable-panel.tsx
  src/pages/analysis/layout-sidebar-item.tsx
  src/pages/analysis/layout-sidebar.tsx
  src/pages/analysis/panels/chessboard/chessboard-panel.css
  src/pages/analysis/panels/chessboard/chessboard-panel.tsx
  src/pages/analysis/panels/controls/controls.tsx
  src/pages/analysis/panels/engineInterpretation/classificationDescription.ts
  src/pages/analysis/panels/engineInterpretation/engine-interpretation.tsx
  src/pages/analysis/panels/engineLines/engine-lines.tsx
  src/pages/analysis/panels/evalHistory/eval-history.tsx
  src/pages/analysis/panels/moveList/move-list.tsx
  src/pages/history/data-table.tsx
  src/pages/start-analysis/start-analysis.tsx
  src/store/analysis.ts
  src/store/layout.ts
  src/store/theme.ts
  src/types/layout.ts
Labels: feature, improvement

#97 Improve/navbar
  public/logo.svg
  src/app.tsx
  src/components/navbar/navbar.tsx
  src/components/ui/navigation-menu.tsx
Labels: style

#98 Style/overhaul
  src/app.tsx
  src/assets/icons/chess_logo.png
  src/assets/icons/chesscom.svg
  src/assets/icons/lichess.png
  src/assets/icons/lichess.svg
  src/assets/icons/react.svg
  src/components/navbar/navbar.tsx
  src/components/ui/button.tsx
  src/components/ui/calendar.tsx
  src/components/ui/card.tsx
  src/components/ui/command.tsx
  src/components/ui/dialog.tsx
  src/components/ui/dropdown-menu.tsx
  src/components/ui/input.tsx
  src/components/ui/navigation-menu.tsx
  src/components/ui/popover.tsx
  src/components/ui/progress.tsx
  src/components/ui/select.tsx
  src/components/ui/slider.tsx
  src/components/ui/switch.tsx
  src/components/ui/tabs.tsx
  src/components/ui/textarea.tsx
  src/components/ui/tooltip.tsx
  src/pages/analysis/panels/controls/controls.tsx
  src/pages/dashboard/columns.tsx
  src/pages/dashboard/dashboard.tsx
  src/pages/dashboard/data-table.tsx
  src/pages/dashboard/overview.tsx
  src/pages/dashboard/statistics.tsx
  src/pages/history/history-page.tsx
  src/pages/login/login.tsx
  src/pages/register/register.tsx
  src/pages/start-analysis/chesscom-select.tsx
  src/pages/start-analysis/lichessorg-select.tsx
  src/pages/start-analysis/start-analysis.tsx
  src/pages/theme/theme.tsx
Labels: style

#99 Improve/move list
  src/data/classifications.ts
  src/i18n.config.ts
  src/i18n/locales/en/moveList.json
  src/i18n/locales/fr/moveList.json
  src/lib/format.ts
  src/pages/analysis/panels/chessboard/chessboard-panel.tsx
  src/pages/analysis/panels/controls/controls.tsx
  src/pages/analysis/panels/moveList/move-list.tsx
  src/store/move-list.ts
Labels: improvement

#101 Fix/history open
  src/api/analysis.ts
  src/api/history.ts
  src/api/index.ts
  src/app.tsx
  src/pages/analysis/analysis.tsx
  src/pages/dashboard/dashboard.tsx
  src/pages/dashboard/data-table.tsx
  src/pages/start-analysis/start-analysis.tsx
  src/types/analysis.ts
Labels: fix

#104 hotfix: fix build errors
  src/lib/analysis.ts
  src/pages/analysis/layout-sidebar-item.tsx
  tsconfig.tsbuildinfo
Labels: hotfix

#103 Hotfix/build
  src/lib/analysis.ts
  src/pages/analysis/layout-sidebar-item.tsx
  tsconfig.tsbuildinfo
Labels: hotfix

#105 docs(navbar): rework docs links
  src/components/navbar/navbar.tsx
  src/i18n/locales/en/navbar.json
  src/i18n/locales/fr/navbar.json
Labels: documentation

#106 Feat/database
  .gitignore
  .storybook/main.ts
  .storybook/manager.ts
  .storybook/preview.ts
  .storybook/theme.ts
  package-lock.json
  package.json
  src/api/database.ts
  src/components/ui/avatar.stories.tsx
  src/components/ui/button.stories.tsx
  src/components/ui/calendar.stories.tsx
  src/components/ui/card.stories.tsx
  src/components/ui/checkbox.stories.tsx
  src/components/ui/command.stories.tsx
  src/components/ui/dialog.stories.tsx
  src/components/ui/dropdown-menu.stories.tsx
  src/components/ui/input.stories.tsx
  src/components/ui/label.stories.tsx
  src/components/ui/select.stories.tsx
  src/pages/analysis/analysis-old.tsx
  src/pages/analysis/analysis.tsx
  src/pages/analysis/layout-sidebar-item.tsx
  src/pages/analysis/panels/controls/controls.tsx
  src/pages/analysis/panels/database/database.tsx
  src/pages/analysis/panels/engineInterpretation/classificationDescription.ts
  src/pages/analysis/panels/engineInterpretation/engine-interpretation.tsx
  src/pages/analysis/panels/moveList/move-list.tsx
  src/store/layout.ts
  src/types/layout.ts
  tailwind.config.js
Labels: feature

#107 Docs and new Features
  .gitignore
  .storybook/main.ts
  .storybook/manager.ts
  .storybook/preview.ts
  .storybook/theme.ts
  package-lock.json
  package.json
  src/api/database.ts
  src/components/navbar/navbar.tsx
  src/components/ui/avatar.stories.tsx
  src/components/ui/button.stories.tsx
  src/components/ui/calendar.stories.tsx
  src/components/ui/card.stories.tsx
  src/components/ui/checkbox.stories.tsx
  src/components/ui/command.stories.tsx
  src/components/ui/dialog.stories.tsx
  src/components/ui/dropdown-menu.stories.tsx
  src/components/ui/input.stories.tsx
  src/components/ui/label.stories.tsx
  src/components/ui/select.stories.tsx
  src/i18n/locales/en/navbar.json
  src/i18n/locales/fr/navbar.json
  src/lib/opening.ts
  src/pages/analysis/analysis.tsx
  src/pages/analysis/layout-sidebar-item.tsx
  src/pages/analysis/panels/controls/controls.tsx
  src/pages/analysis/panels/database/database.tsx
  src/pages/analysis/panels/moveList/move-list.tsx
  src/store/layout.ts
  src/types/layout.ts
  tailwind.config.js
Labels: documentation, feature

#108 improve(start-analysis): add advanced options and rework layout
  package-lock.json
  package.json
  src/components/ui/accordion.tsx
  src/i18n/locales/en/analysis.json
  src/i18n/locales/fr/analysis.json
  src/lib/analysis.ts
  src/pages/start-analysis/chesscom-select.tsx
  src/pages/start-analysis/lichessorg-select.tsx
  src/pages/start-analysis/start-analysis.tsx
  src/schema/analysis.ts
  src/services/stockfish/stockfish.service.ts
  tailwind.config.js
Labels: improvement

#110 Docs/storybook
  package-lock.json
  tailwind.config.js
Labels: documentation

#122 Improve/analysis
  package-lock.json
  package.json
  src/components/chessboard/base.css
  src/components/playerinfo/playerinfo.tsx
  src/components/squareHighlight/square-highlight.tsx
  src/components/ui/collapsible.tsx
  src/components/ui/toggle-group.tsx
  src/components/ui/toggle.tsx
  src/lib/interpretation.ts
  src/pages/analysis/analysis.tsx
  src/pages/analysis/layout-sidebar-item.tsx
  src/pages/analysis/panels/controls/controls.tsx
  src/pages/analysis/panels/engineInterpretation/classificationDescription.ts
  src/pages/analysis/panels/engineInterpretation/engine-interpretation.tsx
  src/pages/analysis/panels/interpretation/interpretation.tsx
  src/pages/dashboard/data-table.tsx
  src/store/layout.ts
  src/styles/index.css
  src/types/interpretation.ts
  src/types/layout.ts
Labels: feature, improvement

#121 doc(code): add documentation code
  src/pages/analysis/analysis-old.tsx
  src/pages/analysis/analysis.tsx
  src/pages/analysis/droppable-panel.tsx
  src/pages/analysis/layout-sidebar-item.tsx
  src/pages/analysis/layout-sidebar.tsx
  src/pages/analysis/panels/chessboard/chessboard-panel.tsx
  src/pages/analysis/panels/controls/controls.tsx
  src/pages/analysis/panels/database/database.tsx
  src/pages/analysis/panels/evalHistory/eval-history.tsx
  src/pages/analysis/panels/moveList/move-list.tsx
  src/pages/dashboard/columns.tsx
  src/pages/dashboard/dashboard.tsx
  src/pages/dashboard/data-table.tsx
  src/pages/login/login.tsx
  src/pages/profile/profile.tsx
  src/pages/register/register.tsx
  src/pages/start-analysis/chesscom-select.tsx
  src/pages/start-analysis/lichessorg-select.tsx
  src/pages/start-analysis/start-analysis.tsx
Labels: documentation

#124 tests(unit): added unit tests for libs
  package-lock.json
  package.json
  src/lib/format.test.ts
  src/lib/opening.test.ts
  src/pages/analysis/analysis-old.tsx
  src/pages/analysis/analysis.tsx
  src/pages/analysis/layout-sidebar-item.tsx
  src/pages/analysis/panels/moveList/move-list.tsx
  src/pages/dashboard/columns.tsx
  src/pages/dashboard/dashboard.tsx
  src/pages/dashboard/data-table.tsx
  src/pages/login/login.tsx
  src/pages/profile/profile.tsx
  src/pages/register/register.tsx
  src/pages/start-analysis/chesscom-select.tsx
  src/pages/start-analysis/lichessorg-select.tsx
  vitest.config.js
Labels: test
